Repository gisaia/ARLAS-web-components, pull requests merged in 2018-07, with the labels that each got.

#152 Fix #150 : Display the slected styles of all stylegroups
  src/components/componentsUtils.ts
  src/components/mapgl/mapgl.component.css
  src/components/mapgl/mapgl.component.html
  src/components/mapgl/mapgl.component.ts
  src/components/mapgl/mapgl.module.ts
  src/components/mapgl/mapgl.schema.json
  src/components/mapgl/model/mapLayers.ts
Labels: type:bug

#154 Add maxZoom,minZoom,scale input
  src/app/mapgl-demo/mapgl-demo.component.html
  src/components/mapgl/mapgl.component.ts
Labels: MAP, type:enhancement

#159 Feature/improve result list
  src/app/results-demo/results-demo.component.html
  src/app/results-demo/results-demo.component.ts
  src/app/results-demo/utils/detailed-data-retriever.ts
  src/assets/i18n/en.json
  src/assets/i18n/fr.json
  src/components/results/model/item.ts
  src/components/results/model/itemComponent.ts
  src/components/results/result-detailed-grid/result-detailed-grid.component.css
  src/components/results/result-detailed-grid/result-detailed-grid.component.html
  src/components/results/result-detailed-grid/result-detailed-grid.component.ts
  src/components/results/result-detailed-item/result-detailed-item.component.html
  src/components/results/result-detailed-item/result-detailed-item.component.ts
  src/components/results/result-grid-tile/result-grid-tile.component.html
  src/components/results/result-list/result-list.component.html
  src/components/results/result-list/result-list.component.ts
  src/components/results/utils/results.utils.ts
Labels: RESULTLIST, type:enhancement

#161 Update mapcomponent configuration schema
  src/components/mapgl/mapgl.component.ts
  src/components/mapgl/mapgl.schema.json
Labels: type:enhancement

#160 Add dropdown in search list
  package.json
  src/app/app.component.css
  src/app/app.component.html
  src/app/results-demo/results-demo.component.css
  src/app/results-demo/results-demo.component.html
  src/app/results-demo/results-demo.component.ts
  src/components/results/model/column.ts
  src/components/results/result-filter/result-filter.component.html
  src/components/results/result-filter/result-filter.component.ts
  src/components/results/result-list/result-list.component.html
  src/components/results/result-list/result-list.component.ts
  src/components/results/results.module.ts
  src/styles.css
Labels: RESULTLIST, type:enhancement

#164 Add option to translate area charts by half data interval
  package-lock.json
  package-release.json
  package.json
  src/components/histogram/histogram.component.ts
  src/components/histogram/histogram.schema.json
  yarn.lock
Labels: type:enhancement

#163 Feature/auto geo sort list
  src/components/results/result-filter/result-filter.component.ts
  src/components/results/result-list/result-list.component.html
  src/components/results/result-list/result-list.component.ts
Labels: RESULTLIST, type:enhancement

#165 Improve draw bbox management
  package-lock.json
  src/components/mapgl/mapgl.component.ts
Labels: MAP, type:bug

#166 Build the id column using fieldsConfiguration instead of fieldsList
  src/components/results/result-list/result-list.component.ts
Labels: type:maintenance

#168 Apply geosort on geo-auto-sort activation
  src/components/results/result-filter/result-filter.component.html
  src/components/results/result-list/result-list.component.html
  src/components/results/result-list/result-list.component.ts
Labels: type:enhancement

#169 Add escape listener to cancel draw bbox
  src/components/mapgl/mapgl.component.ts
Labels: MAP, type:enhancement
