Repository gisaia/ARLAS-web-components, pull requests merged in 2018-09, with the labels that each got.

#177 Remove useless CSS file
  package-release.json
  package.json
  src/styles.css
Labels: type:enhancement

#170 Fix selection disappear powerbars
  src/components/powerbars/powerbars.component.css
  src/components/powerbars/powerbars.component.ts
Labels: POWERBARS, type:bug

#178 Update lock files
  package-lock.json
  yarn.lock
Labels: type:maintenance

#179 Update lock files + fix imports
  package-lock.json
  src/components/histogram/histogram.component.ts
  yarn.lock
Labels: type:maintenance

#180 Add selected item as input
  src/components/results/result-list/result-list.component.ts
Labels: RESULTLIST, type:enhancement

#181 Fix selected input list
  src/components/results/result-list/result-list.component.ts
Labels: RESULTLIST, type:maintenance
