Repository gisaia/ARLAS-web-components, pull requests merged in 2018-12, with the labels that each got.

#192 Fix tbody list height if no filter
  src/app/mapgl-demo/mapgl-demo.component.ts
  src/app/results-demo/results-demo.component.html
  src/components/results/result-list/result-list.component.ts
Labels: RESULTLIST, type:bug

#195 Custom css powerbars with term value
  src/components/powerbars/powerbars.component.html
Labels: POWERBARS, type:enhancement

#196 Fix routing strategy in demo
  package-lock.json
  src/app/app.component.html
  src/app/app.component.ts
  src/app/app.module.ts
  src/index.html
Labels: type:enhancement
