Repository gisaia/ARLAS-web-components, pull requests merged in 2019-01, with the labels that each got.

#197 Add search field on top of powerbars
  src/app/app.module.ts
  src/components/powerbars/powerbars.component.html
  src/components/powerbars/powerbars.component.ts
  src/components/powerbars/powerbars.module.ts
Labels: type:enhancement

#199 Fix mkDoc image version
  mkDocs.sh
  package.json
Labels: type:maintenance

#200 Improve filter field in powerbars
  src/app/powerbars-demo/powerbars-demo.component.html
  src/components/powerbars/powerbars.component.html
  src/components/powerbars/powerbars.component.ts
Labels: type:enhancement

#201 Move geosort action
  src/assets/i18n/en.json
  src/assets/i18n/fr.json
  src/components/results/result-list/result-list.component.css
  src/components/results/result-list/result-list.component.html
  src/components/results/result-list/result-list.component.ts
Labels: RESULTLIST, type:enhancement

#206 Improve powerbars layout
  src/components/powerbars/powerbars.component.css
  src/components/powerbars/powerbars.component.html
  src/components/powerbars/powerbars.component.ts
  src/components/powerbars/powerbars.module.ts
Labels: POWERBARS, type:enhancement

#207 Fix width full powerbars
  src/components/powerbars/powerbars.component.html
  src/components/powerbars/powerbars.component.ts
Labels: POWERBARS, type:bug

#208 Check if source exists before adding it
  src/components/mapgl/mapgl.component.ts
Labels: MAP, type:bug

#210 Emit init value in moveend bus
  src/components/mapgl/mapgl.component.ts
Labels: MAP, type:enhancement

#215 Refactor Histogram and Donuts according to changes of arlas-d3@6.0.0
  package-lock.json
  package-release.json
  package.json
  src/app/donut-demo/donut-demo.component.ts
  src/app/histogram-demo/histogram-demo.component.html
  src/app/histogram-demo/histogram-demo.component.ts
  src/components/donut/donut.component.ts
  src/components/histogram/histogram.component.html
  src/components/histogram/histogram.component.ts
  src/components/index.ts
Labels: type:breaking, type:enhancement

#221 sort powerbar list
  src/components/powerbars/powerbars.component.ts
Labels: POWERBARS, type:bug

#222 Fix color for result list : apply toString() to itemData.get method
  src/components/results/result-item/result-item.component.html
Labels: RESULTLIST, type:bug

#223 Fix color of powerbars and update json schema
  src/components/powerbars/powerbars.component.ts
  src/components/powerbars/powerbars.schema.json
Labels: type:bug
