Repository gisaia/ARLAS-web-components, pull requests merged in 2019-07, with the labels that each got.

#282 Add properties to onMoveResult map
  src/components/mapgl/mapgl.component.ts
  src/components/mapgl/mapgl.component.util.ts
Labels: MAP, type:enhancement

#287 Feature/fix #286
  src/app/mapgl-demo/mapgl-demo.component.html
  src/app/mapgl-demo/mapgl-demo.component.ts
  src/components/mapgl-import/mapgl-import.component.ts
  src/components/mapgl/mapgl.component.ts
Labels: MAP, type:enhancement

#294 Remove unused outputs and unexisting method in HTML file
  src/components/results/result-grid-tile/result-grid-tile.component.ts
  src/components/results/result-item/result-item.component.ts
  src/components/results/result-list/result-list.component.html
Labels: RESULTLIST, type:bug

#295 Fix SelectInBetween and SelectAll bugs
  src/components/results/result-list/result-list.component.ts
Labels: RESULTLIST, type:bug

#296 Update lock files
  package-lock.json
  yarn.lock
Labels: type:maintenance

#297 Emit 'selectedItemEvent' after in between selection
  package-lock.json
  src/components/results/result-list/result-list.component.ts
  yarn.lock
Labels: RESULTLIST, type:bug
