Repository gisaia/ARLAS-web-components, pull requests merged in 2019-10, with the labels that each got.

#311 Add WMTS layer style manager
  package-lock.json
  package-release.json
  package.json
  src/app/app.component.html
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/wmts-layer-manager-demo/wmts-layer-manager-demo.component.css
  src/app/wmts-layer-manager-demo/wmts-layer-manager-demo.component.html
  src/app/wmts-layer-manager-demo/wmts-layer-manager-demo.component.spec.ts
  src/app/wmts-layer-manager-demo/wmts-layer-manager-demo.component.ts
  src/assets/getCap_1.xml
  src/assets/getCap_2.xml
  src/assets/getCap_3.xml
  src/assets/getCap_4.xml
  src/assets/getCap_5.xml
  src/components/wmts-layer-manager/wmts-layer-manager-dialog.component.css
  src/components/wmts-layer-manager/wmts-layer-manager-dialog.component.html
  src/components/wmts-layer-manager/wmts-layer-manager.component.css
  src/components/wmts-layer-manager/wmts-layer-manager.component.html
  src/components/wmts-layer-manager/wmts-layer-manager.component.spec.ts
  src/components/wmts-layer-manager/wmts-layer-manager.component.ts
  src/components/wmts-layer-manager/wmts-layer-manager.module.ts
  src/index.ts
  src/styles.css
  yarn.lock
Labels: type:enhancement

#313 Remove useless assets in build
  gulpfile.js
Labels: type:maintenance

#314 HotFix method accessiblity
  src/components/results/result-detailed-item/result-detailed-item.component.ts
Labels: type:bug

#318 Make show/hide icons customizable
  package-lock.json
  src/app/results-demo/results-demo.component.ts
  src/components/results/result-grid-tile/result-grid-tile.component.css
  src/components/results/result-grid-tile/result-grid-tile.component.html
  src/components/results/result-item/result-item.component.css
  src/components/results/result-item/result-item.component.html
  src/components/results/result-list/result-list.component.css
  src/components/results/result-list/result-list.component.ts
  src/components/results/utils/results.utils.ts
  src/index.ts
  yarn.lock
Labels: RESULTLIST, type:enhancement

#320 Enable style object in map style
  package-lock.json
  package.json
  src/app/mapgl-demo/mapgl-demo.component.html
  src/app/mapgl-demo/mapgl-demo.component.ts
  src/components/mapgl/mapgl.component.ts
  src/components/mapgl/model/mapLayers.ts
  yarn.lock
Labels: MAP, type:enhancement

#321 Fix check box position
  src/components/results/result-grid-tile/result-grid-tile.component.css
Labels: RESULTLIST, type:maintenance

#322 Fix json schema of mapComponent
  package-lock.json
  src/components/mapgl/mapgl.component.ts
  src/components/mapgl/mapgl.schema.json
Labels: type:maintenance

#323 use css classes to style Resultlist table
  src/components/results/result-list/result-list.component.css
  src/components/results/result-list/result-list.component.html
Labels: type:maintenance

#325 Fix draw mode
  src/components/mapgl/mapgl.component.control.ts
  src/components/mapgl/mapgl.component.css
  src/components/mapgl/mapgl.component.ts
Labels: MAP, type:bug

#327 Add tooltip when drawing a polygon that shows how to end drawing
  package-lock.json
  package-release.json
  package.json
  src/components/mapgl/mapgl.component.css
  src/components/mapgl/mapgl.component.html
  src/components/mapgl/mapgl.component.ts
  src/components/mapgl/model/ValidGeomDrawPolygonMode.ts
  yarn.lock
Labels: MAP, type:enhancement
