Repository gisaia/ARLAS-web-components, pull requests merged in 2019-06, with the labels that each got.

#273 Import KML + WKT + GeoJSON
  package-lock.json
  package-release.json
  package.json
  src/app/mapgl-demo/mapgl-demo.component.css
  src/app/mapgl-demo/mapgl-demo.component.html
  src/assets/i18n/en.json
  src/assets/i18n/fr.json
  src/components/mapgl-import/mapgl-import-dialog.component.css
  src/components/mapgl-import/mapgl-import-dialog.component.html
  src/components/mapgl-import/mapgl-import.component.css
  src/components/mapgl-import/mapgl-import.component.ts
  src/components/mapgl-import/mapgl-import.module.ts
  yarn.lock
Labels: MAP, type:enhancement

#274 Fix zip content validation
  src/components/mapgl-import/mapgl-import.component.ts
Labels: type:bug

#279 Add showEmptyGroup input in list
  src/components/results/result-detailed-grid/result-detailed-grid.component.html
  src/components/results/result-detailed-grid/result-detailed-grid.component.ts
  src/components/results/result-detailed-item/result-detailed-item.component.html
  src/components/results/result-detailed-item/result-detailed-item.component.ts
  src/components/results/result-list/result-list.component.html
  src/components/results/result-list/result-list.component.ts
Labels: RESULTLIST, type:enhancement

#281 Add button to clear list selection
  src/components/results/result-list/result-list.component.css
  src/components/results/result-list/result-list.component.html
  src/components/results/result-list/result-list.component.ts
Labels: RESULTLIST, type:enhancement
